[ 2023-04-12 23:01:28,523 ] 19 root - INFO - Starting data ingestion
[ 2023-04-12 23:01:28,523 ] 27 root - INFO - Exporting data from data store to feature store
[ 2023-04-12 23:01:28,986 ] 15 root - INFO - starting Memory reduction of the data frame
[ 2023-04-12 23:01:29,070 ] 39 root - INFO - Memory reduction is completed.
[ 2023-04-12 23:01:29,071 ] 40 root - INFO - Memeory usage decreased to 19.41 Mb (13.3% reduction)
[ 2023-04-12 23:01:29,077 ] 49 root - INFO - Performed train test split on the dataframe
[ 2023-04-12 23:01:29,077 ] 51 root - INFO - Exited split_data_as_train_test method of Data_Ingestion class
[ 2023-04-12 23:01:29,077 ] 59 root - INFO - Exporting train and test file path.
[ 2023-04-12 23:01:29,391 ] 69 root - INFO - Exported train and test file path.
[ 2023-04-12 23:01:29,393 ] 22 root - INFO - Data ingestion completed and artifact: DataIngestionArtifact(trained_file_path='artifact/04_12_2023_23_01_27/data_ingestion/ingested/train.csv', test_file_path='artifact/04_12_2023_23_01_27/data_ingestion/ingested/test.csv')
[ 2023-04-12 23:01:29,485 ] 32 root - INFO - Required number of columns: 83
[ 2023-04-12 23:01:29,485 ] 33 root - INFO - Data frame has columns: 83
[ 2023-04-12 23:01:29,485 ] 32 root - INFO - Required number of columns: 83
[ 2023-04-12 23:01:29,485 ] 33 root - INFO - Data frame has columns: 83
[ 2023-04-12 23:01:30,834 ] 15 root - ERROR - Error occurred python script name [/Users/saurabhbhardwaj/Documents/Microsoft_malware_detection/src/pipeline/training_pipeline.py] line number [65] error message [Error occurred python script name [/Users/saurabhbhardwaj/Documents/Microsoft_malware_detection/src/pipeline/training_pipeline.py] line number [33] error message [Error occurred python script name [/Users/saurabhbhardwaj/Documents/Microsoft_malware_detection/src/components/data_validation.py] line number [130] error message [Error occurred python script name [/Users/saurabhbhardwaj/Documents/Microsoft_malware_detection/src/components/data_validation.py] line number [72] error message ['<' not supported between instances of 'float' and 'str']]]]
Traceback (most recent call last):
  File "/Users/saurabhbhardwaj/Documents/Microsoft_malware_detection/src/components/data_validation.py", line 72, in detect_dataset_drift
    is_same_dist = ks_2samp(d1,d2)
  File "/Users/saurabhbhardwaj/opt/anaconda3/envs/venv/lib/python3.8/site-packages/scipy/stats/stats.py", line 6822, in ks_2samp
    data1 = np.sort(data1)
  File "<__array_function__ internals>", line 5, in sort
  File "/Users/saurabhbhardwaj/opt/anaconda3/envs/venv/lib/python3.8/site-packages/numpy/core/fromnumeric.py", line 991, in sort
    a.sort(axis=axis, kind=kind, order=order)
TypeError: '<' not supported between instances of 'float' and 'str'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/saurabhbhardwaj/Documents/Microsoft_malware_detection/src/components/data_validation.py", line 130, in initiate_data_validation
    status = self.detect_dataset_drift(base_df=train_dataframe,current_df=test_dataframe)
  File "/Users/saurabhbhardwaj/Documents/Microsoft_malware_detection/src/components/data_validation.py", line 94, in detect_dataset_drift
    raise MalwareException(e,sys)
src.exception.MalwareException: Error occurred python script name [/Users/saurabhbhardwaj/Documents/Microsoft_malware_detection/src/components/data_validation.py] line number [72] error message ['<' not supported between instances of 'float' and 'str']

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/saurabhbhardwaj/Documents/Microsoft_malware_detection/src/pipeline/training_pipeline.py", line 33, in start_data_validaton
    data_validation_artifact = data_validation.initiate_data_validation()
  File "/Users/saurabhbhardwaj/Documents/Microsoft_malware_detection/src/components/data_validation.py", line 145, in initiate_data_validation
    raise MalwareException(e,sys)
src.exception.MalwareException: Error occurred python script name [/Users/saurabhbhardwaj/Documents/Microsoft_malware_detection/src/components/data_validation.py] line number [130] error message [Error occurred python script name [/Users/saurabhbhardwaj/Documents/Microsoft_malware_detection/src/components/data_validation.py] line number [72] error message ['<' not supported between instances of 'float' and 'str']]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/saurabhbhardwaj/Documents/Microsoft_malware_detection/src/pipeline/training_pipeline.py", line 65, in run_pipeline
    data_validation_artifact=self.start_data_validaton(data_ingestion_artifact=data_ingestion_artifact)
  File "/Users/saurabhbhardwaj/Documents/Microsoft_malware_detection/src/pipeline/training_pipeline.py", line 36, in start_data_validaton
    raise  MalwareException(e,sys)
src.exception.MalwareException: Error occurred python script name [/Users/saurabhbhardwaj/Documents/Microsoft_malware_detection/src/pipeline/training_pipeline.py] line number [33] error message [Error occurred python script name [/Users/saurabhbhardwaj/Documents/Microsoft_malware_detection/src/components/data_validation.py] line number [130] error message [Error occurred python script name [/Users/saurabhbhardwaj/Documents/Microsoft_malware_detection/src/components/data_validation.py] line number [72] error message ['<' not supported between instances of 'float' and 'str']]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 12, in main
    training_pipeline.run_pipeline()
  File "/Users/saurabhbhardwaj/Documents/Microsoft_malware_detection/src/pipeline/training_pipeline.py", line 67, in run_pipeline
    raise  MalwareException(e,sys)
src.exception.MalwareException: Error occurred python script name [/Users/saurabhbhardwaj/Documents/Microsoft_malware_detection/src/pipeline/training_pipeline.py] line number [65] error message [Error occurred python script name [/Users/saurabhbhardwaj/Documents/Microsoft_malware_detection/src/pipeline/training_pipeline.py] line number [33] error message [Error occurred python script name [/Users/saurabhbhardwaj/Documents/Microsoft_malware_detection/src/components/data_validation.py] line number [130] error message [Error occurred python script name [/Users/saurabhbhardwaj/Documents/Microsoft_malware_detection/src/components/data_validation.py] line number [72] error message ['<' not supported between instances of 'float' and 'str']]]]
